name: Laravel Deploy Github Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Deploy-Project:
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@master

    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run production
    - name: Install Dependencies
      run: composer install --optimize-autoloader --no-dev
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    # Upload code to server
    - name: copy files
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        overwrite: true
        source: "./*"
        target: /public_html/
